### ISSUE TITLE
wrong branch path?

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/flatiron-kitchen#3]
When I ran 'learn open':

```
// ♥ learn open
Getting current lesson...
Forking lesson...
Cloning lesson...
/Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:231:in `read': No such file or directory @ rb_sysopen - /Users/Roberto/Development/code/flatiron-kitchen-v-000/.learn (Errno::ENOENT)
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:231:in `ios_lesson?'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:296:in `bundle_install'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:33:in `run'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:7:in `run'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/bin/learn-open:7:in `<top (required)>'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/bin/learn-open:23:in `load'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/bin/learn-open:23:in `<main>'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Roberto/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[17:02:14] ~
// ♥ cd Development/code/
[17:02:50] code
// ♥ git clone git@github.com:onyoo/flatiron-kitchen-v-000.git
fatal: destination path 'flatiron-kitchen-v-000' already exists and is not an empty directory.
[17:02:53] code
// ♥ cd flatiron-kitchen-v-000/
[17:03:07] (bonus-solution-fields-for) flatiron-kitchen-v-000
// ♥ subl .
```

but this happens sometimes when opening. I also thought it was strange that I didn't get the (master) branch. That turned-out to be a problem.

As it turns-out students (though the first student didn't somehow, or didn't care to report) are somehow getting the (bonus-solution-fields-for) branch instead of the (master) branch. I was trying to deal with all the crazy error messages on the wrong branch for quite a while before realizing the problem. The master branch seems to be working for now.

```
git clone -b master git@github.com:learn-co-students/flatiron-kitchen-v-000.git
```
@jakebrady5

**Comment by onyoo** [comment]
Correction, I just saw the other issue report. I stand corrected.

**Comment by AnnJohn** [comment]
hi @onyoo sorry for the delay but this should be fixed. Thanks!
